(define-key evil-insert-state-map (kbd "S-<down>") 'evil-next-visual-line)
(define-key evil-insert-state-map (kbd "S-<up>") 'evil-previous-visual-line)
(define-key evil-motion-state-map (kbd "S-<down>") 'evil-next-visual-line)
(define-key evil-motion-state-map (kbd "S-<up>") 'evil-previous-visual-line)
(define-key evil-normal-state-map (kbd "S-<down>") 'evil-next-visual-line)
(define-key evil-normal-state-map (kbd "S-<up>") 'evil-previous-visual-line)
(define-key evil-visual-state-map (kbd "S-<down>") 'evil-next-visual-line)
(define-key evil-visual-state-map (kbd "S-<up>") 'evil-previous-visual-line)

(define-key evil-normal-state-map (kbd "DEL") 'evil-delete-backward-char-without-register)
(define-key evil-normal-state-map [delete] 'evil-delete-char-without-register)
(define-key evil-visual-state-map (kbd "DEL") 'evil-delete-without-register)
(define-key evil-visual-state-map [delete] 'evil-delete-without-register)

(define-key evil-normal-state-map [escape] 'keyboard-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'ptb/minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'ptb/minibuffer-keyboard-quit)
(define-key minibuffer-local-map [escape] 'ptb/minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'ptb/minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'ptb/minibuffer-keyboard-quit)
(global-set-key [escape] 'evil-exit-emacs-state)

(global-set-key (kbd "<end>") 'end-of-line)
(global-set-key (kbd "<home>") 'beginning-of-line)
(global-set-key (kbd "RET") 'newline-and-indent)

(global-set-key (kbd "C-l") 'evil-search-highlight-persist-remove-all)

(global-set-key (kbd "s-a") 'mark-whole-buffer)
(global-set-key (kbd "s-n") 'ptb/new-untitled-frame)
(global-set-key (kbd "s-q") 'ptb/kill-current-buffer)
(global-set-key (kbd "s-t") 'ptb/new-untitled-buffer)
(global-set-key (kbd "s-w") 'ptb/kill-current-buffer)
(global-set-key (kbd "s-{") 'previous-buffer)
(global-set-key (kbd "s-}") 'next-buffer)
